// Master list of all administrative modules and pages categorized for dynamic role matrix management
export const ROLE_PERMISSION_CATEGORIES = [
  {
    category: "Core Operations & LMS",
    pages: [
      {
        id: "admin_dashboard",
        title: "Admin Dashboard",
        path: "/admin",
        module: "analytics",
        description: "System overview, visitor analytics, key metrics and summaries",
        actions: ["view"],
      },
      {
        id: "blogs",
        title: "Blogs & Articles",
        path: "/admin/blogs",
        module: "blogs",
        description: "Publish, edit and manage industry articles and blog posts",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "market_updates",
        title: "LPG Market Updates",
        path: "/admin/market-updates",
        module: "market-updates",
        description: "LPG international price trends, monthly BERC tariffs and industry market data",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "courses",
        title: "Courses & Curricula",
        path: "/admin/courses",
        module: "courses",
        description: "Course lessons, modules, pricing and video curricula",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "enrollments",
        title: "Course Enrollments & Sales",
        path: "/admin/courses/enrollments",
        module: "courses",
        description: "Enrolled learners history, revenue and purchase tracking",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "certificates",
        title: "Certificates Issuance",
        path: "/admin/certificates",
        module: "certificates",
        description: "Learner certificates, serial validation and issue records",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "safety_guidelines",
        title: "Safety Guidelines & Authorities",
        path: "/admin/safety-guidelines",
        module: "safety_guidelines",
        description: "LPG safety manuals, regulatory agencies, stakeholder documents & PDFs",
        actions: ["view", "create", "edit", "delete"],
      },
    ],
  },
  {
    category: "Access Control & Administration",
    pages: [
      {
        id: "users",
        title: "User Registry",
        path: "/admin/users",
        module: "users",
        description: "Platform accounts, roles, access levels and user profiles",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "roles",
        title: "Roles & Permissions",
        path: "/admin/roles",
        module: "roles",
        description: "Custom role creation, matrix permissions and staff privileges",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "settings",
        title: "System Settings",
        path: "/admin/settings",
        module: "settings",
        description: "Platform configurations, general contact information, and preferences",
        actions: ["view", "edit"],
      },
    ],
  },
  {
    category: "Communication & Marketing",
    pages: [
      {
        id: "messages",
        title: "Messages & Inquiries",
        path: "/admin/messages",
        module: "messages",
        description: "Contact form inquiries, customer support and communication",
        actions: ["view", "edit", "delete"],
      },
      {
        id: "comments",
        title: "Comments Moderation",
        path: "/admin/comments",
        module: "comments",
        description: "Public blog reader comments, moderation and replies",
        actions: ["view", "edit", "delete"],
      },
      {
        id: "advertisements",
        title: "Advertisements & Banners",
        path: "/admin/advertisements",
        module: "advertisements",
        description: "Hero promo banners, sidebars and sponsored placements",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "sms",
        title: "Bulk SMS Broadcasting",
        path: "/admin/sms",
        module: "sms",
        description: "SMS gateway dispatch, templates and delivery tracking",
        actions: ["view", "create", "delete"],
      },
      {
        id: "email",
        title: "Email Campaigns",
        path: "/admin/email",
        module: "email",
        description: "Email broadcasts, newsletters and subscriber lists",
        actions: ["view", "create", "delete"],
      },
      {
        id: "newsletter",
        title: "Newsletter Subscribers",
        path: "/admin/newsletter",
        module: "newsletter",
        description: "Subscribed readers, broadcast logs, email list and campaign reach",
        actions: ["view", "delete"],
      },
    ],
  },
  {
    category: "Subscriptions & Commerce",
    pages: [
      {
        id: "subscriptions",
        title: "Subscription Management",
        path: "/admin/subscriptions",
        module: "subscriptions",
        description: "Paid subscription tiers, membership validity and records",
        actions: ["view", "create", "edit", "delete"],
      },
      {
        id: "coupons",
        title: "Coupons & Vouchers",
        path: "/admin/coupons",
        module: "subscriptions",
        description: "Discount coupons, promo codes and voucher campaigns",
        actions: ["view", "create", "edit", "delete"],
      },
    ],
  },
  {
    category: "Public Website CMS Pages",
    pages: [
      {
        id: "pages_home",
        title: "Home Page CMS",
        path: "/admin/pages/home",
        module: "pages_home",
        description: "Home hero slider, stats, featured sections and welcome text",
        actions: ["view", "edit"],
      },
      {
        id: "pages_about",
        title: "About Us CMS",
        path: "/admin/pages/about",
        module: "pages_about",
        description: "Mission, vision, leadership team and company profile content",
        actions: ["view", "edit"],
      },
      {
        id: "pages_blogs",
        title: "Blog Listing Page CMS",
        path: "/admin/pages/blogs",
        module: "pages_blogs",
        description: "Public blog catalog header, featured banners and categories",
        actions: ["view", "edit"],
      },
      {
        id: "pages_contact",
        title: "Contact Us CMS",
        path: "/admin/pages/contact",
        module: "pages_contact",
        description: "Official addresses, hotline numbers, email and maps",
        actions: ["view", "edit"],
      },
      {
        id: "pages_safety",
        title: "Safety Guidelines CMS",
        path: "/admin/pages/safety-guidelines",
        module: "pages_safety",
        description: "LPG cylinder safety manuals, handling guides and checklists",
        actions: ["view", "edit"],
      },
      {
        id: "pages_market",
        title: "LPG Market Updates CMS",
        path: "/admin/pages/market-updates",
        module: "pages_market",
        description: "Government pricing notices, market revisions and updates",
        actions: ["view", "edit"],
      },
      {
        id: "pages_courses",
        title: "Training & Quiz CMS",
        path: "/admin/pages/courses",
        module: "pages_courses",
        description: "LMS public landing page banner, introduction and FAQs",
        actions: ["view", "edit"],
      },
      {
        id: "pages_acts",
        title: "Acts & Rules CMS",
        path: "/admin/pages/acts-and-rules",
        module: "pages_acts",
        description: "Energy regulatory acts, gazette publications and rules",
        actions: ["view", "edit"],
      },
      {
        id: "pages_terms",
        title: "Terms & Conditions CMS",
        path: "/admin/pages/terms",
        module: "pages_terms",
        description: "Website terms of service, disclaimers and legal terms",
        actions: ["view", "edit"],
      },
      {
        id: "pages_privacy",
        title: "Privacy Policy CMS",
        path: "/admin/pages/privacy",
        module: "pages_privacy",
        description: "Data privacy regulations, cookie usage and privacy policy",
        actions: ["view", "edit"],
      },
      {
        id: "pages_faq",
        title: "FAQ & Help Center CMS",
        path: "/admin/pages/faq",
        module: "pages_faq",
        description: "Frequently asked questions and support answers",
        actions: ["view", "edit"],
      },
      {
        id: "pages_subscription",
        title: "Subscription & Plans CMS",
        path: "/admin/pages/subscription",
        module: "pages_subscription",
        description: "Public subscription tier pricing and plan cards",
        actions: ["view", "edit"],
      },
    ],
  },
];
